/*
Ory Identities API

This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more.

API version:
Contact: office@ory.sh
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the DeviceAuthnAndroidRootOfTrust type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeviceAuthnAndroidRootOfTrust{}

// DeviceAuthnAndroidRootOfTrust struct for DeviceAuthnAndroidRootOfTrust
type DeviceAuthnAndroidRootOfTrust struct {
	DeviceLocked         *bool   `json:"device_locked,omitempty"`
	VerifiedBootHash     []int32 `json:"verified_boot_hash,omitempty"`
	VerifiedBootKey      []int32 `json:"verified_boot_key,omitempty"`
	VerifiedBootState    *int64  `json:"verified_boot_state,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DeviceAuthnAndroidRootOfTrust DeviceAuthnAndroidRootOfTrust

// NewDeviceAuthnAndroidRootOfTrust instantiates a new DeviceAuthnAndroidRootOfTrust object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeviceAuthnAndroidRootOfTrust() *DeviceAuthnAndroidRootOfTrust {
	this := DeviceAuthnAndroidRootOfTrust{}
	return &this
}

// NewDeviceAuthnAndroidRootOfTrustWithDefaults instantiates a new DeviceAuthnAndroidRootOfTrust object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeviceAuthnAndroidRootOfTrustWithDefaults() *DeviceAuthnAndroidRootOfTrust {
	this := DeviceAuthnAndroidRootOfTrust{}
	return &this
}

// GetDeviceLocked returns the DeviceLocked field value if set, zero value otherwise.
func (o *DeviceAuthnAndroidRootOfTrust) GetDeviceLocked() bool {
	if o == nil || IsNil(o.DeviceLocked) {
		var ret bool
		return ret
	}
	return *o.DeviceLocked
}

// GetDeviceLockedOk returns a tuple with the DeviceLocked field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceAuthnAndroidRootOfTrust) GetDeviceLockedOk() (*bool, bool) {
	if o == nil || IsNil(o.DeviceLocked) {
		return nil, false
	}
	return o.DeviceLocked, true
}

// HasDeviceLocked returns a boolean if a field has been set.
func (o *DeviceAuthnAndroidRootOfTrust) HasDeviceLocked() bool {
	if o != nil && !IsNil(o.DeviceLocked) {
		return true
	}

	return false
}

// SetDeviceLocked gets a reference to the given bool and assigns it to the DeviceLocked field.
func (o *DeviceAuthnAndroidRootOfTrust) SetDeviceLocked(v bool) {
	o.DeviceLocked = &v
}

// GetVerifiedBootHash returns the VerifiedBootHash field value if set, zero value otherwise.
func (o *DeviceAuthnAndroidRootOfTrust) GetVerifiedBootHash() []int32 {
	if o == nil || IsNil(o.VerifiedBootHash) {
		var ret []int32
		return ret
	}
	return o.VerifiedBootHash
}

// GetVerifiedBootHashOk returns a tuple with the VerifiedBootHash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceAuthnAndroidRootOfTrust) GetVerifiedBootHashOk() ([]int32, bool) {
	if o == nil || IsNil(o.VerifiedBootHash) {
		return nil, false
	}
	return o.VerifiedBootHash, true
}

// HasVerifiedBootHash returns a boolean if a field has been set.
func (o *DeviceAuthnAndroidRootOfTrust) HasVerifiedBootHash() bool {
	if o != nil && !IsNil(o.VerifiedBootHash) {
		return true
	}

	return false
}

// SetVerifiedBootHash gets a reference to the given []int32 and assigns it to the VerifiedBootHash field.
func (o *DeviceAuthnAndroidRootOfTrust) SetVerifiedBootHash(v []int32) {
	o.VerifiedBootHash = v
}

// GetVerifiedBootKey returns the VerifiedBootKey field value if set, zero value otherwise.
func (o *DeviceAuthnAndroidRootOfTrust) GetVerifiedBootKey() []int32 {
	if o == nil || IsNil(o.VerifiedBootKey) {
		var ret []int32
		return ret
	}
	return o.VerifiedBootKey
}

// GetVerifiedBootKeyOk returns a tuple with the VerifiedBootKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceAuthnAndroidRootOfTrust) GetVerifiedBootKeyOk() ([]int32, bool) {
	if o == nil || IsNil(o.VerifiedBootKey) {
		return nil, false
	}
	return o.VerifiedBootKey, true
}

// HasVerifiedBootKey returns a boolean if a field has been set.
func (o *DeviceAuthnAndroidRootOfTrust) HasVerifiedBootKey() bool {
	if o != nil && !IsNil(o.VerifiedBootKey) {
		return true
	}

	return false
}

// SetVerifiedBootKey gets a reference to the given []int32 and assigns it to the VerifiedBootKey field.
func (o *DeviceAuthnAndroidRootOfTrust) SetVerifiedBootKey(v []int32) {
	o.VerifiedBootKey = v
}

// GetVerifiedBootState returns the VerifiedBootState field value if set, zero value otherwise.
func (o *DeviceAuthnAndroidRootOfTrust) GetVerifiedBootState() int64 {
	if o == nil || IsNil(o.VerifiedBootState) {
		var ret int64
		return ret
	}
	return *o.VerifiedBootState
}

// GetVerifiedBootStateOk returns a tuple with the VerifiedBootState field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceAuthnAndroidRootOfTrust) GetVerifiedBootStateOk() (*int64, bool) {
	if o == nil || IsNil(o.VerifiedBootState) {
		return nil, false
	}
	return o.VerifiedBootState, true
}

// HasVerifiedBootState returns a boolean if a field has been set.
func (o *DeviceAuthnAndroidRootOfTrust) HasVerifiedBootState() bool {
	if o != nil && !IsNil(o.VerifiedBootState) {
		return true
	}

	return false
}

// SetVerifiedBootState gets a reference to the given int64 and assigns it to the VerifiedBootState field.
func (o *DeviceAuthnAndroidRootOfTrust) SetVerifiedBootState(v int64) {
	o.VerifiedBootState = &v
}

func (o DeviceAuthnAndroidRootOfTrust) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeviceAuthnAndroidRootOfTrust) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DeviceLocked) {
		toSerialize["device_locked"] = o.DeviceLocked
	}
	if !IsNil(o.VerifiedBootHash) {
		toSerialize["verified_boot_hash"] = o.VerifiedBootHash
	}
	if !IsNil(o.VerifiedBootKey) {
		toSerialize["verified_boot_key"] = o.VerifiedBootKey
	}
	if !IsNil(o.VerifiedBootState) {
		toSerialize["verified_boot_state"] = o.VerifiedBootState
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DeviceAuthnAndroidRootOfTrust) UnmarshalJSON(data []byte) (err error) {
	varDeviceAuthnAndroidRootOfTrust := _DeviceAuthnAndroidRootOfTrust{}

	err = json.Unmarshal(data, &varDeviceAuthnAndroidRootOfTrust)

	if err != nil {
		return err
	}

	*o = DeviceAuthnAndroidRootOfTrust(varDeviceAuthnAndroidRootOfTrust)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "device_locked")
		delete(additionalProperties, "verified_boot_hash")
		delete(additionalProperties, "verified_boot_key")
		delete(additionalProperties, "verified_boot_state")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDeviceAuthnAndroidRootOfTrust struct {
	value *DeviceAuthnAndroidRootOfTrust
	isSet bool
}

func (v NullableDeviceAuthnAndroidRootOfTrust) Get() *DeviceAuthnAndroidRootOfTrust {
	return v.value
}

func (v *NullableDeviceAuthnAndroidRootOfTrust) Set(val *DeviceAuthnAndroidRootOfTrust) {
	v.value = val
	v.isSet = true
}

func (v NullableDeviceAuthnAndroidRootOfTrust) IsSet() bool {
	return v.isSet
}

func (v *NullableDeviceAuthnAndroidRootOfTrust) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeviceAuthnAndroidRootOfTrust(val *DeviceAuthnAndroidRootOfTrust) *NullableDeviceAuthnAndroidRootOfTrust {
	return &NullableDeviceAuthnAndroidRootOfTrust{value: val, isSet: true}
}

func (v NullableDeviceAuthnAndroidRootOfTrust) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeviceAuthnAndroidRootOfTrust) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
